<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">

<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>

<xsl:template match="/">
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Sitemap — BAiSED</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: #050508;
      color: #ededed;
      font-family: 'Geist Mono', 'SF Mono', Monaco, 'Cascadia Code', 'Roboto Mono', Consolas, monospace;
      line-height: 1.6;
      padding: 2rem;
    }
    .container {
      max-width: 900px;
      margin: 0 auto;
      background: #0a0c12;
      border: 1px solid #1a2a3a;
      padding: 2rem;
    }
    h1 {
      font-size: 1.5rem;
      font-weight: 700;
      letter-spacing: 0.05em;
      margin-bottom: 0.5rem;
      color: #ededed;
    }
    p {
      font-size: 0.75rem;
      color: #787878;
      margin-bottom: 2rem;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 0.75rem;
    }
    thead {
      border-bottom: 1px solid #1a1f2e;
    }
    th {
      text-align: left;
      padding: 0.75rem 1rem 0.75rem 0;
      font-weight: 500;
      color: #787878;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
    td {
      padding: 0.75rem 1rem 0.75rem 0;
      border-top: 1px solid #1a1f2e;
    }
    td:first-child {
      color: #ededed;
    }
    a {
      color: #0052FF;
      text-decoration: none;
      transition: color 0.2s;
    }
    a:hover {
      color: #3380FF;
    }
    .footer {
      margin-top: 2rem;
      padding-top: 1.5rem;
      border-top: 1px solid #1a1f2e;
      font-size: 0.625rem;
      color: #444;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>SITEMAP</h1>
    <p>XML sitemap for search engines. <a href="/">← Back to site</a></p>

    <table>
      <thead>
        <tr>
          <th>URL</th>
          <th>Last Modified</th>
          <th>Priority</th>
        </tr>
      </thead>
      <tbody>
        <xsl:for-each select="sitemap:urlset/sitemap:url">
          <tr>
            <td>
              <a>
                <xsl:attribute name="href">
                  <xsl:value-of select="sitemap:loc"/>
                </xsl:attribute>
                <xsl:value-of select="sitemap:loc"/>
              </a>
            </td>
            <td>
              <xsl:value-of select="concat(substring(sitemap:lastmod, 0, 11))"/>
            </td>
            <td>
              <xsl:value-of select="sitemap:priority"/>
            </td>
          </tr>
        </xsl:for-each>
      </tbody>
    </table>

    <div class="footer">
      Generated by Next.js · baised.dev
    </div>
  </div>
</body>
</html>
</xsl:template>

</xsl:stylesheet>
